# Generated by Django 2.2 on 2022-01-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0002_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='reviever',
            new_name='reciever',
        ),
    ]
