# Generated by Django 2.2 on 2022-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0003_auto_20220125_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('group', 'user')},
        ),
    ]
