# Generated by Django 2.2 on 2022-01-28 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0004_auto_20220128_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='final_server.Group'),
            preserve_default=False,
        ),
    ]
