# Generated by Django 2.2.5 on 2022-01-30 17:16

from django.db import migrations, models
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0005_groupmessage_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='delete_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=django_bleach.models.BleachField(null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=django_bleach.models.BleachField(null=True),
        ),
    ]
