# Generated by Django 2.2.5 on 2022-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0006_auto_20220130_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
