# Generated by Django 2.2.5 on 2022-01-30 17:59

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('final_server', '0007_auto_20220130_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='message',
            field=django_bleach.models.BleachField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='content',
            field=django_bleach.models.BleachField(max_length=250, null=True),
        ),
    ]
